### ISSUE TITLE
requires an array?

### ISSUE THREAD

**Issue by Harxy** [tmiyamon/acts-as-taggable-array-on#7]
I don't know what is going on here, almost certainly user error on my part, but acts_as_taggable needs to be passed an array from the form to work, and that's lead to some really shonky code on my part. What am I doing wrong here?

```
  def note_params
    params.require(:note)
      .permit(:tag_list,
                  :priority,
                  :date_show,
                  :body)
  end
```

This leads to all sorts of problems when I try and save the record, saying that "method uniq is undefined for String" or whatever, basically because tag list is just a string.

So I've had to put this crazy thing in the controller:
`@note.tag_list = @note.tag_list.split(',')`
before I @note.save to make it work.
Which can't be right, can it?

What am I missing? :(

**Comment by bryanrite** [comment]
If you are passing the tags in as an array,  you need to let strong_parameters know as well:

```ruby
def note_params
  params.require(:note).permit(:priority, :date_show, :body, tag_list: [])
end
```

Otherwise strong params sees an array where you only allow primitive types so its filtered out.
